[book]
authors = ["Shielded Labs <https://shieldedlabs.net>"]
language = "en"
multilingual = false
src = "src"
title = "The Zebra Crosslink Book"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["theme/css/custom.css"]
